### ISSUE TITLE
#bugs

### ISSUE THREAD

**Issue by cleiveliu** [ruxtain/c-algorithms#1]
https://github.com/ruxtain/c-algorithms/blob/4fc13344c9b4add962afc43b4e3682ea43d856f9/data-structures/linked-stack.c#L60
if the stack s has no element then call p->next will cause an error, I think it's better be written as 
```c
 for (link_stack *p = s->next;  p; p=p->next)
or
 for (link_stack *p = s->next; p != NULL; p=p->next)  
```

**Comment by Charlesl86** [comment]
Issues and been with this.
